### ISSUE TITLE
Wiz bulbs ?

### ISSUE THREAD

**Issue by konrad51** [CaiB/ColorChord.NET#20] opened 2023-09-21 18:58 UTC
Is there any way to make ColorChord.NET work with the Philips Wiz Bulbs ?

**Comment by CaiB** [comment] 2023-09-28 23:23
Hi there!

Sorry for the late reply, I've been busy with moving.

From a cursory look, it appears that those bulbs only have a web-based API, which goes through the Philips servers. Do you know of any way to directly control them without this additional hop?

If they can only be controlled via the internet, I'm afraid the added latency would completely ruin the effect ColorChord tries to achieve.

**Comment by konrad51** [comment] 2023-09-29 11:36
Hi, thanks for responding. I am not any kind of programmer or coder, but I have been looking into these Wiz Bulbs since I have some. To the best of my knowledge, the internet is used to assign ip addresses to each bulb and after that they can be controlled through wifi. The Android app that assigns the ip addresses is found at:

https://www.wizconnected.com/en-us/explore-wiz/app 


I can list some info I have found on the web that pertains to controlling these bulbs: 

https://www.reddit.com/r/wiz/comments/1582jfx/guide_to_controlling_a_wiz_lightplug_via_windows/?rdt=44192

https://aleksandr.rogozin.us/blog/2021/8/13/hacking-philips-wiz-lights-via-command-line

https://limitedresults.com/2019/02/pwn-the-wiz-connected/

https://cycling74.com/forums/controlling-wiz-wifi-led-rgb-lightbulbs

https://ehbtj-com.translate.goog/electronics/control-smart-light-bulb-wiz-with-esp32/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc

https://github.com/sbidy/pywizlight

https://pypi.org/project/wizcon/

https://github.com/10xJSChad/BulbScript-for-Wiz-Lights

Hopefully this information can help you to get these Wiz bulbs to work with ColorChord. Thanks for looking into this.

**Comment by konrad51** [comment] 2023-10-20 14:16
Hi, just checking in with you. I've been checking for the last few weeks for your response to my last post. I don't know if you are interested in following up on this or not or are too busy. If you can't pursue this , you can just mark it closed. Thanks.

**Comment by CaiB** [comment] 2023-10-21 03:57
Hello,

Apologies again for the delay. I've been pretty busy recently. I looked over some of the links you sent, and it appears this would be reasonably easy to implement, so I think I should be able to get around to doing it sometime soon.

I'll let you know once I have code ready to test.

Thanks for your interest in CC.NET!

**Comment by CaiB** [comment] 2023-11-05 09:01
Hello again,

I've added a first try of Wiz bulb support. Please download the latest autobuild (at least v0.7.0.211) and give it a try, and let me know what works and what doesn't.

It seems like you need to enable "Allow local communication" in the mobile app for the bulbs to be usable over UDP.

Then, in the CC.NET config.json file, add this section in Outputs:
```json
{
    "Type": "Wiz",
    "Name": "WizTest",
    "VisualizerName": "SampleLinear",
    "BulbIPs": ["192.168.10.10", "192.168.10.15"]
}
```
Where VisualizerName corresponds with a visualizer you have in the config, and BulbIPs is a list of the bulbs you want to control, in the order listed. To get these IPs, you can leave the list blank, run CC.NET with this config, and it will try to run discovery to find all of the bulbs on your network and list them in the console.

I can't test any of this myself, so I'm just going off the documentation and code I've found, so please show me the output you get when you have a chance to try it.

Thanks!

**Comment by konrad51** [comment] 2023-11-05 13:28
Thanks for the response.

I am using the following config.json file:

{
    "Source":
    {
        "Type": "WASAPILoopback",
        "Device": "default",
        "ShowDeviceInfo": true
    },
    "NoteFinder":
    {
        "Type": "BaseNoteFinder"
    },
    "Visualizers":
    [
        {
            "Type": "Linear",
            "Name": "SampleLinear",
            "LEDCount": 5,
            "IsCircular": true,
            "FrameRate": 60,
            "LightSiding": 1.0,
            "SteadyBright": false,
            "LEDFloor": 0.1,
            "LEDLimit": 1.0,
            "SaturationAmplifier": 1.6,
            "Enable": true
        }
    ],
    "Outputs":
    [
        {   "Type": "Wiz",
            "Name": "WizTest",
            "VisualizerName": "SampleLinear",
            "BulbIPs": ["192.168.254.50","192.168.254.54","192.168.254.42","192.168.254.41","192.168.254.49"]
        },
    
        {
            "Type": "DisplayOpenGL",
            "Name": "SampleDisplay",
            "VisualizerName": "SampleLinear",
            "Modes":
            [
                {
                    "Type": "SmoothStrip"
                }
            ],
            "WindowWidth": 800,
            "WindowHeight": 150
        }
    ],
    "Controllers":
    [

    ]
}

This is what I get in command console:


C:\Users\schultz\Downloads\ColorChord.NET-autobuild-v0.7.0.211>ColorChord.NET.exe
[INF] Reading and applying configuration file "config.json"...
[INF] Reading config for BaseNoteFinder.
[INF] Created audio source of type "ColorChord.NET.NoteFinder.BaseNoteFinder".
[INF] Reading config for WASAPILoopback.
[INF] Created audio source of type "ColorChord.NET.Sources.WASAPILoopback".
[INF] Render Devices:
[INF] [0]: "SAMSUNG (High Definition Audio Device)" = "{0.0.0.00000000}.{63d4ffb7-6103-4a82-89a0-3ce14e5fc802}"
[INF] [1]: "Speakers (2- High Definition Audio Device)" = "{0.0.0.00000000}.{d22be60c-daa5-4cb9-a669-a4972fb48793}"
[INF] Capture Devices:
[INF] [0]: "Microphone (2- High Definition Audio Device)" = "{0.0.1.00000000}.{688e4315-64d7-44bb-81fe-9080cf510856}"
[INF] Using default render device.
[INF] Audio format is 2 channel, 44100Hz sample rate, 32b per sample.
[INF] Default transaction period is 101587 ticks, minimum is 29025 ticks.
[INF] Reading config for Linear.
[INF] Reading config for Wiz.
[INF] Got Wiz Discovery Response from 192.168.254.21: "{"method":"getSystemConfig","params":{}}"
[INF] Reading config for DisplayOpenGL.
[INF] Finished reading display modes under "SampleDisplay".
[WRN] Could not find valid "Controllers" definition. No controllers will be configured.
[INF] Finished processing config file.


Bulbs are not doing anything when music is played, but computer display is responding to music.

**Comment by CaiB** [comment] 2023-11-05 13:31
Hmm, the config looks good. However, it looks like only 1 bulb responded to the discovery request, `192.168.254.21` (which you don't seem to be using). Are you sure all of the bulbs have been configured to allow local control in the app? If you've used any of the other software (like the options you linked previously), have they worked with local control?

**Comment by CaiB** [comment] 2023-11-05 13:32
Oh wait, `192.168.254.21` is probably your computer. So it looks like no bulbs are responding.

**Comment by konrad51** [comment] 2023-11-05 13:49
Yes, 192.168.254.21 is my computer. When I run ColorChord with no bulb IPs entered I get:

C:\Users\schultz\Downloads\ColorChord.NET-autobuild-v0.7.0.211>ColorChord.NET.exe
[INF] Reading and applying configuration file "config.json"...
[INF] Reading config for BaseNoteFinder.
[INF] Created audio source of type "ColorChord.NET.NoteFinder.BaseNoteFinder".
[INF] Reading config for WASAPILoopback.
[INF] Created audio source of type "ColorChord.NET.Sources.WASAPILoopback".
[INF] Render Devices:
[INF] [0]: "SAMSUNG (High Definition Audio Device)" = "{0.0.0.00000000}.{63d4ffb7-6103-4a82-89a0-3ce14e5fc802}"
[INF] [1]: "Speakers (2- High Definition Audio Device)" = "{0.0.0.00000000}.{d22be60c-daa5-4cb9-a669-a4972fb48793}"
[INF] Capture Devices:
[INF] [0]: "Microphone (2- High Definition Audio Device)" = "{0.0.1.00000000}.{688e4315-64d7-44bb-81fe-9080cf510856}"
[INF] Using default render device.
[INF] Audio format is 2 channel, 44100Hz sample rate, 32b per sample.
[INF] Default transaction period is 101587 ticks, minimum is 29025 ticks.
[INF] Reading config for Linear.
[INF] Reading config for Wiz.
[WRN] Wiz sender "WizTest" has 1 bulb(s) configured, but the visualizer is outputting 5 unit(s). It is recommended to change the visualizer settings to match.
[INF] Got Wiz Discovery Response from 192.168.254.21: "{"method":"getSystemConfig","params":{}}"
[INF] Got Wiz Discovery Response from 192.168.254.42: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0da4b2","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Reading config for DisplayOpenGL.
[INF] Finished reading display modes under "SampleDisplay".
[WRN] Could not find valid "Controllers" definition. No controllers will be configured.
[INF] Finished processing config file.
[INF] Got Wiz Discovery Response from 192.168.254.50: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0e8732","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.54: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0e860e","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.41: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e92f09e","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.49: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0d99d6","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}

**Comment by CaiB** [comment] 2023-11-05 13:53
Oh interesting. I'm not sure why they don't respond to discovery if you send data.

Regardless, let me add some more code to see what's going on. Hang tight...

**Comment by CaiB** [comment] 2023-11-05 14:02
Alright, give autobuild 212 a try and see if that works (make sure to put the IPs back in the config)

**Comment by konrad51** [comment] 2023-11-05 14:33
This is what I get with no IPs entered:


C:\Users\schultz\Downloads\ColorChord.NET-autobuild-v0.7.0.212>ColorChord.NET.exe
[INF] Reading and applying configuration file "config.json"...
[INF] Reading config for BaseNoteFinder.
[INF] Created audio source of type "ColorChord.NET.NoteFinder.BaseNoteFinder".
[INF] Reading config for WASAPILoopback.
[INF] Created audio source of type "ColorChord.NET.Sources.WASAPILoopback".
[INF] Render Devices:
[INF] [0]: "SAMSUNG (High Definition Audio Device)" = "{0.0.0.00000000}.{63d4ffb7-6103-4a82-89a0-3ce14e5fc802}"
[INF] [1]: "Speakers (2- High Definition Audio Device)" = "{0.0.0.00000000}.{d22be60c-daa5-4cb9-a669-a4972fb48793}"
[INF] Capture Devices:
[INF] [0]: "Microphone (2- High Definition Audio Device)" = "{0.0.1.00000000}.{688e4315-64d7-44bb-81fe-9080cf510856}"
[INF] Using default render device.
[INF] Audio format is 2 channel, 44100Hz sample rate, 32b per sample.
[INF] Default transaction period is 101587 ticks, minimum is 29025 ticks.
[INF] Reading config for Linear.
[INF] Reading config for Wiz.
Unhandled exception. System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at ColorChord.NET.Outputs.Wiz.Start() in C:\projects\colorchord-net\ColorChord.NET\Outputs\Wiz.cs:line 63
   at ColorChord.NET.ColorChord.CreateObject[BaseType](String fullName, JToken configEntry, Boolean complexConfig, Boolean provideControllerInterface) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 312
   at ColorChord.NET.ColorChord.ReadAndApplyOutputs(JObject JSON) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 245
   at ColorChord.NET.ColorChord.ReadConfig() in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 142
   at ColorChord.NET.ColorChord.Main(String[] args) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 55

This with IPs Inserted:


C:\Users\schultz\Downloads\ColorChord.NET-autobuild-v0.7.0.212>ColorChord.NET.exe
[INF] Reading and applying configuration file "config.json"...
[INF] Reading config for BaseNoteFinder.
[INF] Created audio source of type "ColorChord.NET.NoteFinder.BaseNoteFinder".
[INF] Reading config for WASAPILoopback.
[INF] Created audio source of type "ColorChord.NET.Sources.WASAPILoopback".
[INF] Render Devices:
[INF] [0]: "SAMSUNG (High Definition Audio Device)" = "{0.0.0.00000000}.{63d4ffb7-6103-4a82-89a0-3ce14e5fc802}"
[INF] [1]: "Speakers (2- High Definition Audio Device)" = "{0.0.0.00000000}.{d22be60c-daa5-4cb9-a669-a4972fb48793}"
[INF] Capture Devices:
[INF] [0]: "Microphone (2- High Definition Audio Device)" = "{0.0.1.00000000}.{688e4315-64d7-44bb-81fe-9080cf510856}"
[INF] Using default render device.
[INF] Audio format is 2 channel, 44100Hz sample rate, 32b per sample.
[INF] Default transaction period is 101587 ticks, minimum is 29025 ticks.
[INF] Reading config for Linear.
[INF] Reading config for Wiz.
Unhandled exception. System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at ColorChord.NET.Outputs.Wiz.Start() in C:\projects\colorchord-net\ColorChord.NET\Outputs\Wiz.cs:line 63
   at ColorChord.NET.ColorChord.CreateObject[BaseType](String fullName, JToken configEntry, Boolean complexConfig, Boolean provideControllerInterface) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 312
   at ColorChord.NET.ColorChord.ReadAndApplyOutputs(JObject JSON) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 245
   at ColorChord.NET.ColorChord.ReadConfig() in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 142
   at ColorChord.NET.ColorChord.Main(String[] args) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 55

**Comment by CaiB** [comment] 2023-11-05 14:46
This error is usually caused by either another instance of the same program, or another program using the port. Check in Task Manager to make sure there aren't any copies of CC.NET left running, and try it again.
If that still doesn't work, when CC.NET is closed, run this from a PowerShell window started with "Run as Administrator": `netstat -ab | sls :38899 -Context 0,1`, it will tell you if something (and what) is using the port.

It might also just be my code being broken, so let me know what you find.

**Comment by konrad51** [comment] 2023-11-05 15:07
OK, here's what I got:

C:\Users\schultz\Downloads\ColorChord.NET-autobuild-v0.7.0.212>ColorChord.NET.exe
[INF] Reading and applying configuration file "config.json"...
[INF] Reading config for BaseNoteFinder.
[INF] Created audio source of type "ColorChord.NET.NoteFinder.BaseNoteFinder".
[INF] Reading config for WASAPILoopback.
[INF] Created audio source of type "ColorChord.NET.Sources.WASAPILoopback".
[INF] Render Devices:
[INF] [0]: "SAMSUNG (High Definition Audio Device)" = "{0.0.0.00000000}.{63d4ffb7-6103-4a82-89a0-3ce14e5fc802}"
[INF] [1]: "Speakers (2- High Definition Audio Device)" = "{0.0.0.00000000}.{d22be60c-daa5-4cb9-a669-a4972fb48793}"
[INF] Capture Devices:
[INF] [0]: "Microphone (2- High Definition Audio Device)" = "{0.0.1.00000000}.{688e4315-64d7-44bb-81fe-9080cf510856}"
[INF] Using default render device.
[INF] Audio format is 2 channel, 44100Hz sample rate, 32b per sample.
[INF] Default transaction period is 101587 ticks, minimum is 29025 ticks.
[INF] Reading config for Linear.
[INF] Reading config for Wiz.
[INF] Got Wiz Discovery Response from 192.168.254.21: "{"method":"getSystemConfig","params":{}}"
[INF] Got Wiz Discovery Response from 192.168.254.41: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e92f09e","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Reading config for DisplayOpenGL.
[INF] Finished reading display modes under "SampleDisplay".
[WRN] Could not find valid "Controllers" definition. No controllers will be configured.
[INF] Finished processing config file.
[INF] Got Wiz Discovery Response from 192.168.254.41: "{"method":"setState","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.41: "{"method":"setPilot","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.54: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0e860e","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.42: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0da4b2","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.54: "{"method":"setState","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.42: "{"method":"setState","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.54: "{"method":"setPilot","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.42: "{"method":"setPilot","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.50: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0e8732","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.50: "{"method":"setState","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.50: "{"method":"setPilot","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.49: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0d99d6","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.49: "{"method":"setState","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.49: "{"method":"setPilot","id":1,"env":"pro","result":{"success":true}}"

I have one bulb with the diffuser removed and looking at it, it appears that all the RBG leds are lit continuously .... not changing in response to the volume, tempo, or frequency of the music.

**Comment by CaiB** [comment] 2023-11-05 15:14
OK. When CC.NET starts up, I dimly light R, G and B, and then it's supposed to override that with colour data as it runs. I've just changed the code slightly, try autobuild 213 and see if that works any better.

**Comment by konrad51** [comment] 2023-11-05 15:26
Could not tell any difference . Here's what I got:


C:\Users\schultz\Downloads\ColorChord.NET-autobuild-v0.7.0.213>ColorChord.NET.exe
[INF] Reading and applying configuration file "config.json"...
[INF] Reading config for BaseNoteFinder.
[INF] Created audio source of type "ColorChord.NET.NoteFinder.BaseNoteFinder".
[INF] Reading config for WASAPILoopback.
[INF] Created audio source of type "ColorChord.NET.Sources.WASAPILoopback".
[INF] Render Devices:
[INF] [0]: "SAMSUNG (High Definition Audio Device)" = "{0.0.0.00000000}.{63d4ffb7-6103-4a82-89a0-3ce14e5fc802}"
[INF] [1]: "Speakers (2- High Definition Audio Device)" = "{0.0.0.00000000}.{d22be60c-daa5-4cb9-a669-a4972fb48793}"
[INF] Capture Devices:
[INF] [0]: "Microphone (2- High Definition Audio Device)" = "{0.0.1.00000000}.{688e4315-64d7-44bb-81fe-9080cf510856}"
[INF] Using default render device.
[INF] Audio format is 2 channel, 44100Hz sample rate, 32b per sample.
[INF] Default transaction period is 101587 ticks, minimum is 29025 ticks.
[INF] Reading config for Linear.
[INF] Reading config for Wiz.
[INF] Got Wiz Discovery Response from 192.168.254.21: "{"method":"getSystemConfig","params":{}}"
[INF] Reading config for DisplayOpenGL.
[INF] Got Wiz Discovery Response from 192.168.254.42: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0da4b2","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.50: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0e8732","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.50: "{"method":"setState","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.42: "{"method":"setState","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.54: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0e860e","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.41: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e92f09e","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.54: "{"method":"setState","id":1,"env":"pro","result":{"success":true}}"
[INF] Finished reading display modes under "SampleDisplay".
[INF] Got Wiz Discovery Response from 192.168.254.42: "{"method":"setPilot","id":1,"env":"pro","result":{"success":true}}"
[WRN] Could not find valid "Controllers" definition. No controllers will be configured.
[INF] Got Wiz Discovery Response from 192.168.254.50: "{"method":"setPilot","id":1,"env":"pro","result":{"success":true}}"
[INF] Finished processing config file.
[INF] Got Wiz Discovery Response from 192.168.254.41: "{"method":"setState","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.54: "{"method":"setPilot","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.41: "{"method":"setPilot","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.49: "{"method":"getSystemConfig","env":"pro","result":{"mac":"444f8e0d99d6","homeId":8828377,"roomId":13214482,"rgn":"eu","moduleName":"ESP24_SHRGBC_01","fwVersion":"1.30.1","groupId":0,"ping":0}}"
[INF] Got Wiz Discovery Response from 192.168.254.49: "{"method":"setState","id":1,"env":"pro","result":{"success":true}}"
[INF] Got Wiz Discovery Response from 192.168.254.49: "{"method":"setPilot","id":1,"env":"pro","result":{"success":true}}"

**Comment by CaiB** [comment] 2023-11-05 15:32
Oh, I made a dumb mistake. Try autobuild 214. It should now spam the console with a "Wiz sending" line for every frame (and hopefully work)

**Comment by konrad51** [comment] 2023-11-05 15:43
You nailed it !!! Working great now ! Thanks so much for taking the time and trouble to do this. I really appreciate it.

**Comment by CaiB** [comment] 2023-11-05 15:50
Sweet! I just pushed a new version that gets rid of the console spam, and improves efficiency a bit. Could you test that and just verify that I haven't broken it?

Thanks!

**Comment by konrad51** [comment] 2023-11-05 15:54
Still working great !!! Thank you so much !

**Comment by CaiB** [comment] 2023-11-05 15:55
Also, if you'd be willing to record a 30-second or so video of it working, I'm curious to see what the latency is like (and I'm always curious to see how people are using CC.NET), that would be much appreciated!

I'll close the issue now.

**Closed as completed by CaiB** 2023-11-05 15:55 UTC
Labels: enhancement

**Comment by konrad51** [comment] 2023-11-05 15:57
OK. I will try to do a video. How do I post it ?

**Comment by CaiB** [comment] 2023-11-05 15:58
Whatever is most convenient for you. You could just upload it to OneDrive or similar and post a link, or upload it to YouTube, etc.

**Comment by konrad51** [comment] 2023-11-05 16:00
Will try to do that later today or tomorrow if I can . Thanks !
